repos:
  - repo: https://github.com/odwyersoftware/brunette
    rev: 0.2.2
    hooks:
      - id: brunette
        args: [-l 79, --single-quotes]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ['-m','3', '--trailing-comma', 'true']
        name: isort (python)
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: [--in-place, --remove-all-unused-imports, --ignore-init-module-imports]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace