from polls.views.adds import *
from polls.views.helpers import *
from polls.views.highscore import *
from polls.views.history import *
from polls.views.homepage import *
from polls.views.login import *
from polls.views.pie_graph import *
from polls.views.registration import *
from polls.views.statistics import *
from polls.views.userpage import *
