from .adds import *
from .helpers import *
from .highscore import *
from .history import *
from .homepage import *
from .login import *
from .pie_graph import *
from .registration import *
from .statistics import *
