# Generated by Django 3.1.1 on 2020-09-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardgame', models.CharField(max_length=50)),
                ('minNumberOfPlayers', models.IntegerField(default=0)),
                ('maxNumberOfPlayers', models.IntegerField(default=0)),
                ('numberOfGames', models.IntegerField(default=0)),
                ('totalTime', models.DurationField(default=0)),
            ],
        ),
    ]
