# Generated by Django 3.1.1 on 2020-09-16 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgames',
            name='totalTime',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
