# Generated by Django 3.1.1 on 2020-09-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200916_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgames',
            name='lastTimePlayed',
            field=models.DateField(auto_now=True),
        ),
    ]
