# Generated by Django 3.1.1 on 2020-09-20 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_boardgames_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgames',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.player'),
            preserve_default=False,
        ),
    ]
