# Generated by Django 3.1.1 on 2020-09-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_boardgames_lasttimeplayed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardgames',
            old_name='boardgame',
            new_name='name',
        ),
    ]
