# Generated by Django 3.1.1 on 2020-10-02 15:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200921_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplay',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 17, 38, 22, 786040)),
        ),
        migrations.AlterField(
            model_name='gameplay',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameplay', to='polls.boardgames'),
        ),
    ]
