# Generated by Django 3.1.1 on 2020-09-18 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200917_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('NumberOfPlayers', models.IntegerField(default=0)),
                ('time', models.DurationField(default=datetime.timedelta(0))),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('boardgame', models.CharField(max_length=50)),
                ('game_ID', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
