# Generated by Django 3.1.1 on 2020-09-19 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_gameplay_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgames',
            name='lastTimePlayed',
        ),
        migrations.RemoveField(
            model_name='boardgames',
            name='numberOfGames',
        ),
        migrations.RemoveField(
            model_name='boardgames',
            name='totalTime',
        ),
        migrations.RemoveField(
            model_name='player',
            name='boardgame',
        ),
        migrations.RemoveField(
            model_name='player',
            name='game_ID',
        ),
        migrations.RemoveField(
            model_name='player',
            name='order',
        ),
        migrations.RemoveField(
            model_name='player',
            name='points',
        ),
        migrations.AlterField(
            model_name='gameplay',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.boardgames'),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('gp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.gameplay')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.player')),
            ],
        ),
    ]
