# Generated by Django 3.1.1 on 2020-10-03 20:05

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201002_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplay',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 22, 5, 35, 67127)),
        ),
        migrations.AlterField(
            model_name='gameplay',
            name='name',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='polls.boardgames',
            ),
        ),
    ]
