# Generated by Django 3.1.1 on 2020-10-05 16:49

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20201003_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                (
                    'basegame',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='polls.boardgames',
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='gameplay',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 18, 49, 24, 558028)),
        ),
        migrations.CreateModel(
            name='UsedExpansion',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('used', models.BooleanField(default=False)),
                (
                    'e_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='polls.expansion',
                    ),
                ),
                (
                    'gp_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='polls.gameplay',
                    ),
                ),
            ],
        ),
    ]
