# Generated by Django 3.1.1 on 2020-10-07 16:22

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20201005_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplay',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 18, 22, 41, 575434)),
        ),
    ]
