# Generated by Django 3.1.1 on 2020-10-14 19:59

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20201007_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='gameplay',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 21, 59, 44, 734814)),
        ),
    ]
