# Generated by Django 3.1.1 on 2020-12-05 12:06

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20201205_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplay',
            name='with_results',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gameplay',
            name='date',
            field=models.DateTimeField(
                default=datetime.datetime(2020, 12, 5, 13, 6, 46, 880801)
            ),
        ),
    ]
