# Generated by Django 3.1.7 on 2022-01-02 14:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20211027_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgames',
            name='bgg_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gameplay',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 15, 9, 4, 893965)),
        ),
        migrations.CreateModel(
            name='OwnExpansion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.expansion')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.player')),
            ],
        ),
        migrations.CreateModel(
            name='OwnBoardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.boardgames')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.player')),
            ],
        ),
    ]
