# Generated by Django 3.1.7 on 2022-01-17 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20220116_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='player_order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlayerSpecifics',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                (
                    'bg_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='polls.boardgames',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='results',
            name='player_specifics',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='polls.playerspecifics',
            ),
        ),
    ]
