# Generated by Django 3.1.7 on 2022-01-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20220117_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgames',
            name='type',
        ),
        migrations.AddField(
            model_name='boardgames',
            name='img_link',
            field=models.URLField(
                default='https://cf.geekdo-images.com/zxVVmggfpHJpmnJY9j-k1w__square100/img/siQ9W5848OomWFJZY_SWYef6rpw=/100x100/filters:strip_icc()/pic1657689.jpg',
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='maxplaytime',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='minage',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='minplaytime',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='rank',
            field=models.DecimalField(decimal_places=2, default=5.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
