# Generated by Django 3.1.7 on 2022-01-31 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20220129_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgames',
            name='basegame',
            field=models.ManyToManyField(related_name='_boardgames_basegame_+', to='polls.Boardgames'),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='standalone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usedexpansion',
            name='e_id_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.boardgames'),
        ),
    ]
