# Generated by Django 3.1.7 on 2022-01-31 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20220131_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownexpansion',
            name='e_id',
        ),
        migrations.RemoveField(
            model_name='ownexpansion',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='usedexpansion',
            name='e_id',
        ),
        migrations.RenameField(
            model_name='usedexpansion',
            old_name='e_id_new',
            new_name='e_id',
        ),
        migrations.DeleteModel(
            name='Expansion',
        ),
        migrations.DeleteModel(
            name='OwnExpansion',
        ),
    ]
