# Generated by Django 4.1 on 2022-09-13 00:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0025_scoringspecifics_scoringtable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardgames",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="gameplay",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="scoringspecifics",
            name="bg_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_category",
                to="polls.boardgames",
            ),
        ),
        migrations.AlterField(
            model_name="scoringtable",
            name="result_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_table",
                to="polls.results",
            ),
        ),
    ]
